language: cpp
# run on new infrastructure
sudo: false
cache: apt
# requires gcc >= 4.7 for C++11
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7
before_install:
  - export CXX=g++-4.7 CC=gcc-4.7
script:
  - make -j
  - make test
